import { StandardTableView } from "std-widgets.slint";
export component HelloWorld inherits Window {
    width: 230px;
    height: 200px;
    in-out property <[[StandardListViewItem]]> row_data: [
        [ { text: "Item 1.1" }, { text: "Item 1.2" } ],
        [ { text: "Item 2.1" }, { text: "Item 2.2" }],
        [ { text: "Item 3.1" }, { text: "Item 3.2" } ],
        [ { text: "Item 4.1" }, { text: "Item 4.2" } ],
        [ { text: "Item 5.1" }, { text: "Item 5.2" } ],
        [ { text: "Item 6.1" }, { text: "Item 6.2" } ]
    ];
}
