import { StandardTableView } from "std-widgets.slint";
export component HelloWorld inherits Window {
    width: 230px;
    height: 200px;
    in-out property <[ [string] ]> table_data: [];
    StandardTableView {
        vertical-stretch: 0;

        sort-ascending(index) => {
            TableViewPageAdapter.sort_ascending(index);
        }
    
        sort-descending(index) => {
            TableViewPageAdapter.sort-descending(index);
        } 
        
        columns: [
            { title: "Nom" },
            { title: "Prénom" }
        ];
    
        rows: TableViewPageAdapter.row_data;
    }
}


export global TableViewPageAdapter {
    
    callback sort_ascending(int);
    callback sort_descending(int);
    
    in-out property <[[StandardListViewItem]]> row_data: [
        [ { text: "Item 1.1", clicked : {} }, { text: "Item 1.2" }, { text: "Item 1.3" }, { text: "Item 1.4" }, ],
        [ { text: "Item 2.1" }, { text: "Item 2.2" }, { text: "Item 2.3" }, { text: "Item 2.4" } ],
        [ { text: "Item 3.1" }, { text: "Item 3.2" }, { text: "Item 3.3" }, { text: "Item 3.4" }, ],
        [ { text: "Item 4.1" }, { text: "Item 4.2" }, { text: "Item 4.3" }, { text: "Item 4.4" }, ],
        [ { text: "Item 5.1" }, { text: "Item 5.2" }, { text: "Item 5.3" }, { text: "Item 5.4" }, ],
        [ { text: "Item 6.1" }, { text: "Item 6.2" }, { text: "Item 6.3" }, { text: "Item 6.4" }, ],
    ];
}